name = "codegen"
[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
gleamy_lights = ">= 2.3.1 and < 3.0.0"
gleamyshell = ">= 2.0.2 and < 3.0.0"
[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.3.1 and < 2.0.0"
